HFB weighted median subtraction
chime-experiment/ch_pipeline pull request #225
Opened 2023-11-23 19:09 UTC by arashcosmology

2023-11-28 21:25 UTC, rikvl requested changes

2023-11-28 21:25 UTC, rikvl commented on ch_pipeline/hfb/analysis.py
> +        diff = data - median[:, :, None, :]
```suggestion
        diff = data - median[:, :, np.newaxis, :]
```

2023-11-28 21:25 UTC, rikvl commented on ch_pipeline/hfb/analysis.py
> +        out.weight[:] = weight[:]
```suggestion
        out.hfb[:] = diff
        out.weight[:] = weight
```
Not 100% sure, but I think the `[:]` is not necessary

2024-01-29 22:38 UTC, jrs65 requested changes

2024-01-29 22:38 UTC, jrs65 commented on ch_pipeline/hfb/analysis.py
> +        binary_weight = mask.astype(float)
I prefer to explicitly set the precision. In this case `np.float32` would suffice.

2024-01-29 22:38 UTC, jrs65 commented on ch_pipeline/hfb/analysis.py
> +        is used in weighted median
There is a convention for docstrings that should be followed. They should be a one line short description (max 88 chars), and then additional details in a subsequent paragraph.

2024-01-30 15:35 UTC, rikvl approved these changes

2024-01-30 16:15 UTC, merged